### ISSUE TITLE
非常感谢您开了PTA的做题插件，但是我在使用

### ISSUE THREAD

**Issue by NightGlowww** [jinzcdev/vscode-pintia#1]
但是我在使用过程中，无法submit，提示无操作权限
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/44762336/185783555-ddeeee10-9028-412d-babf-1afa888fb97f.png">

[INFO] Read the usersession from the "/Users/night/.pintia/user.json"
[HTTP Get] https://pintia.cn/api/u/current
[INFO] Read the cache of dashboard from the "/Users/night/.pintia/cache/dashboard.json"
[INFO] Read the cache of problem sets from the "/Users/night/.pintia/cache/problemSets.json"
[INFO] Read the problem list from the "/Users/night/.pintia/cache/1298273728383766528/PROGRAMMING.json"
[INFO] Refetch user's exams
[HTTP Get] https://pintia.cn/api/problem-sets/1298273728383766528/exams
[HTTP Get] https://pintia.cn/api/problem-sets/1298273728383766528/exams
[HTTP Get] https://pintia.cn/api/problem-sets/1298273728383766528/exam-problem-status
[INFO] Read the problem detail from the "/Users/night/.pintia/cache/1298273728383766528/1298273797619142705.json"
[INFO] Clear the cache from the "/Users/night/.pintia/cache"
[HTTP Get] https://pintia.cn/api/problem-sets/1298273728383766528/problems/1298273797619142705
[HTTP Get] https://pintia.cn/api/problem-sets/1298273728383766528/exams
[HTTP Get] https://pintia.cn/api/problem-sets/1298273728383766528/problems/1298273797619142705
[INFO] Read the problem detail from the "/Users/night/.pintia/cache/1298273728383766528/1298273797619142705.json"
[HTTP Get] https://pintia.cn/api/problem-sets/1298273728383766528/exams
[HTTP Get] https://pintia.cn/api/problem-sets/1298273728383766528/exams
[HTTP Post] https://pintia.cn/api/exams/1556613598733283328/submissions
{"details":[{"problemId":"0","problemSetProblemId":"1298273797619142705","programmingSubmissionDetail":{"compiler":"GCC","program":"\n\n123"}}],"problemType":"PROGRAMMING"}
{"code":"PERMISSION_DENIED","message":"无操作权限"}

**Comment by jinzcdev** [comment]
这是因为您选择的是《教材》类目下的题集，这类题集需要购买对应的教材，输入读者验证码后才能答题，插件中加了锁的题集表示还未解锁，如果提交代码则会提示无权限

**Comment by NightGlowww** [comment]
但是我已经买了教材，是否可以增加验证码的功能呢？

**Comment by jinzcdev** [comment]
购买教材之后，是否在网页上验证过呢？

![image](https://user-images.githubusercontent.com/33695160/186799978-bb58a97b-00d2-4937-8417-4005718627d0.jpeg)

因为验证的功能在网页使用也很方便，所以最初没考虑加这个功能。后续也可能会增加

**Comment by NightGlowww** [comment]
我验证过了，所以我才想说能不能在VS Code里面进行刷题，真的特别好用
<img width="1937" alt="image" src="https://user-images.githubusercontent.com/44762336/186800492-da7453ee-7fbc-4def-8ca2-a05270b0c6ef.png">

**Comment by jinzcdev** [comment]
请问你能确定你网页上验证过题集的账号和在VSCode中的账号是同一个吗。因为我发现网页上你的用户名和登录在VSCode上的用户名并不相同。

![image](https://user-images.githubusercontent.com/33695160/186810154-0dbfae38-6916-469a-977f-1ec166c04329.jpeg)

**Comment by NightGlowww** [comment]
我刚刚看了一下，发现我的微信账号绑定的并非是我的PTA账号，用微信扫描登录后发现是其他的人账号，我不知道是为什么。重新解除绑定后恢复正常了，谢谢您！！！
<img width="826" alt="image" src="https://user-images.githubusercontent.com/44762336/186836304-e57595d9-a250-4c48-b122-8743b6b6c5a3.png">
<img width="1860" alt="image" src="https://user-images.githubusercontent.com/44762336/186836349-8f0b1e8e-b112-47de-805d-40b98c12dab9.png">

**Comment by jinzcdev** [comment]
👍 感谢支持!!
