### ISSUE TITLE
关于题目集

### ISSUE THREAD

**Issue by ambitiuswisdom** [jinzcdev/vscode-pintia#2]
是否可以完善一下题目集的功能，使拓展界面可以显示并进入网页版中的“我的题目集”中的内容

**Comment by jinzcdev** [comment]
您好，该插件的设计初衷是将刷题、写代码的过程整合进编辑器中。“我的题目集”中许多题集包函判断题、选择题等题型，其在网页版中也能较为方便的使用，如果后续增加该部分功能，可能也只会支持 **编程题** 的部分。
