### ISSUE TITLE
g++编译断开

### ISSUE THREAD

**Issue by zzb011024** [jinzcdev/vscode-pintia#3]
由于codenow创建的文件题号和题名有空格导致g++编译找不到文件

**Comment by jinzcdev** [comment]
您好，麻烦提供一下编译器提示错误的日志

**Comment by zzb011024** [comment]
C:\Users\17840>g++ 1001 害死人不偿命的(3n+1)猜想.cpp -o 1001 害死人不偿命的(3n+1)猜想.exe -Wall -O2 -m64 -static-libgcc -fexec-charset=GBK && "g:\pta\.pintia\codes\"1001 害死人不偿命的(3n+1)猜想.exe
g++: error: 1001: No such file or directory
g++: error: 害死人不偿命的(3n+1)猜想.cpp: No such file or directory
g++: error: 害死人不偿命的(3n+1)猜想.exe: No such file or directory
g++: fatal error: no input files
compilation terminated.

我想是否可以在code now时创建文件名去掉中间的空格

**Comment by jinzcdev** [comment]
如果你是手动在终端编译源代码的话，需要在空格前加上 `\` 转译符，或者使用 `""` 把文件名包裹起来；我不清楚你的编译指令是如何触发的
- 如果是使用 VS Code 中的 [C/C++](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) 插件，你点击 `Run C/C++ File`，编译命令会自动给文件加上双引号；
- 如果你用的是 [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner)，则不会自动添加双引号，这可能是个 Bug

这里还是推荐你使用前者来编译运行代码。

---

自定义文件名的功能，我在后续应该会添加，但会在一段时间之后
