### ISSUE TITLE
关于我的题目集

### ISSUE THREAD

**Issue by ChenxiMiku** [jinzcdev/vscode-pintia#4]
能否加入我的题目集中的编程题部分？

**Comment by jinzcdev** [comment]
该部分功能会在以后加入，但会在一段时间之后。

**Comment by jinzcdev** [comment]
《我的题目集》已在 #13 之后的版本中得到支持，可以在 VSCode 上更新到最新的版本。发布日志见 [v0.7.1](https://github.com/jinzcdev/vscode-pintia/releases/tag/v0.7.1)
