### ISSUE TITLE
为每个题目集设置单独的目录进行存放

### ISSUE THREAD

**Issue by lumenofwhy** [jinzcdev/vscode-pintia#5]
如题，能否在生成题目文件时，将每个题目集中的题目存放在对应目录中。

如下图所示：
![Snipaste_2023-01-25_21-45-27](https://user-images.githubusercontent.com/112168810/214579498-9e396cbc-c48c-4e99-bc5b-59bae5f51a57.png)

**Comment by jinzcdev** [comment]
你好，这个功能刚刚已实现并且发布，可在设置中配置是否启用。新版本可以在插件商店更新。

<img width="968" alt="截屏2023-01-25 23 20 01" src="https://user-images.githubusercontent.com/33695160/214602410-1bcdc06c-2461-4d0a-a81b-7582bba741b2.png">

**Comment by lumenofwhy** [comment]
还可以将生成的bin文件统一存放在习题集路径下的.pintia中

**Comment by jinzcdev** [comment]
bin 文件是编译器产生的，更改它的输出路径不是这个插件该做的，也无法实现。如果你认为这些中间文件让目录变得杂乱，我建议用以下几种方式解决：

1. 为你的题库目录建立一个 Git 仓库，将不需要的文件写进 `.gitignore` 中，之后可以用 `git clean -fX` 命令清除被忽略的文件
2. 如果你使用 Linux/macOS，可以在编写设置一个命令别名在其中构建函数，如 `alias ji='buildcpp(){g++ -o a $1; ./a; rm ./a;};buildcpp'`，可以在终端用 `ji` 命令编译运行源代码，产生的可执行文件会在命令执行结束后被删除。这里别名设置成 `ji`，是因为非常顺手 😄 
3. 创建一个脚本清除掉不需要的文件

总之，方法有很多。

**Comment by lumenofwhy** [comment]
感谢😊
