### ISSUE TITLE
无法加载题库

### ISSUE THREAD

**Issue by uutea2023** [jinzcdev/vscode-pintia#6]
![搜狗高速浏览器截图20240224224951](https://github.com/jinzcdev/vscode-pintia/assets/154799812/7b7d60c8-7af4-490c-83a3-9c8b549d0500)
提示如下：
[INFO] Read the user session from the "C:\Users\BlackCat\.pintia\user.json"
[HTTP Get] https://pintia.cn/api/u/current
[INFO] Read the cache of dashboard from the "C:\Users\BlackCat\.pintia\cache\dashboard.json"
[INFO] Read the cache of problem sets from the "C:\Users\BlackCat\.pintia\cache\problemSets.json"
[HTTP Get] https://pintia.cn/api/problem-sets/14/problem-summaries
[HTTP Get] https://pintia.cn/api/problem-sets/14/exam-problem-list?problem_type=CODE_COMPLETION&page=0&limit=200
[INFO] Refetching user's exams
[HTTP Get] https://pintia.cn/api/problem-sets/14/exam-problem-status
Error: examStatus is undefined

**Comment by jinzcdev** [comment]
你好，我测了一下，我这边是没问题的。这个错误，如果 api 没有变更的话，一般是因为缺少登录凭证导致的。你退出登录后重新尝试一下

**Comment by uutea2023** [comment]
好的，谢谢。重新登录也不行，但是最后我进入网站把题库手动点开一次就可以打开了，只要点开就可以在VSCODE打开，没点过的就会打不开。总算解决了 ^^

**Comment by jinzcdev** [comment]
Hi，最近尝试复现了一下这个问题。因为要在列表中显示题目是否已通过，所以插件中调用这个 summary 接口获取用户对该题集的做题情况。如果之前用户从未打开过这个题集，这个 summary 可能没被系统初始化，从而导致上面的问题。

**Comment by jinzcdev** [comment]
该问题已在 #13 之后的版本中修复，可以在 VSCode 上更新到最新的版本。发布日志见 [v0.7.1](https://github.com/jinzcdev/vscode-pintia/releases/tag/v0.7.1)
